### PR TITLE
feat: Enable strict mode and fix corresponding types.

### PR DESCRIPTION
**Pull request by zewish**

### CODE REVIEW

**Review by p-mcgowan — APPROVED** [review]
generation seems good

**Comment by zewish** [comment]
@j-d-carmichael, could you please have a look. This is a small non-breaking fix, which finally allows us to create projects with proper strict mode.

**Comment by j-d-carmichael** [comment]
This has been my Achilles heel for a while in TS... from reading your code here i assume this is effectively extending the Express Response?

```
declare global {
  namespace Express {
    export interface Response {
      // src/http/nodegen/middleware/inferResponseType.ts
      inferResponseType: (
        dataOrPath: any,
        status: number,
        produces?: string,
        outputMap?: Record<string, any>
      ) => any;
    }
  }
}
```

**Comment by zewish** [comment]
@j-d-carmichael, you are right. We effectively do that in the middleware which ads this function, so this should be correct.

**Comment by j-d-carmichael** [comment]
Look good to me

**Pull request merged**
