### PR TITLE
chore: express and jsonwebtoken updated

### PR DESCRIPTION
**Pull request by j-d-carmichael**
as the title says

### CODE REVIEW

**Review by p-mcgowan — APPROVED** [review]
lgtm

**Comment by j-d-carmichael** [comment]
> if this is about audits - [GHSA-rv95-896h-c2vc](https://github.com/advisories/GHSA-rv95-896h-c2vc)
> 
> will need to bump express again once that's resolved

'twas triggered by them yea.. no doubt we will be notified by them again when then jump up to the next version.

**Comment by p-mcgowan** [comment]
I just resolved this in my project with package json overrides (since the patch is in a beta and our project has express as a transient dep from other libs)

```json
{
"overrides": {
    "express": "^5.0.0-beta.3"
  }
 }
```

I think for the tpl here we either need to install the beta temporarily or wait for the patch to be in a mainline release

**Comment by j-d-carmichael** [comment]
> I just resolved this in my project with package json overrides (since the patch is in a beta and our project has express as a transient dep from other libs)
> 
> ```json
> {
> "overrides": {
>     "express": "^5.0.0-beta.3"
>   }
>  }
> ```
> 
> I think for the tpl here we either need to install the beta temporarily or wait for the patch to be in a mainline release
> 
> edit: nevermind - 4.19.2 works just fine, my mistake. This pr is fine, ill have to update my overrides to the mainline version instead of the beta

yea we ran this on a project with no issue

**Pull request merged**
