### PR TITLE
chore: deps. audit fixes and remove mostly unused lib

### PR DESCRIPTION
**Pull request by p-mcgowan**
- audit fix for prod, dev deps still have warnings
- remove request-ip from packages, use a simpler pattern.
  - the request-ip packages just checks a few extra headers, if we really expect those to show up we can just check for more headers in our own lib and save a few deps

### CODE REVIEW

**Review by j-d-carmichael — COMMENTED** [review]
I can't approve this until I've checked the ip  package. Alternatively can you extract the ip stuffs into its own pr?

**Comment by p-mcgowan** [comment]
force pushed just the audit bump - moved the package removal to https://github.com/acr-lfr/generate-it-typescript-server/pull/229

**Comment by j-d-carmichael** [comment]
Cool cool

The change log on request ip doesn't actually talk about any breaking changes on their major 2 to 3 bump :/

**Comment by p-mcgowan** [comment]
ye it was a major semver but realistically could have been minor or patch.

will merge to make the pipelinea happy

**Pull request merged**
