### PR TITLE
Add source map support

### PR DESCRIPTION
**Pull request by Celleb**
Add source map support

### CODE REVIEW

**Comment by j-d-carmichael** [comment]
I'm not sure we need this in the default server stack as the stack is not using webpack.

**Comment by p-mcgowan** [comment]
would say source map support is a great dev feature,but using it as default can bloat prod files - i think it's a pretty easy opt-in at the top level for teams that want to use it

**Comment by Celleb** [comment]
> I'm not sure we need this in the default server stack as the stack is not using webpack.

I am not sure what webpack has to do with this. Maybe you can clarify.

**Comment by Celleb** [comment]
This change does not generate the source maps so it won't bloat prod files. This plugin is just responsible for linking sources to error stack traces. As @p-mcgowan  has said it's quite important for development. Currently when there are errors the source files references are those in the build folder and this is quite counter productive.

Source map generation is the responsibility of the typescript compiler so this will not change that. If there are no source maps the plugin will just ignore.

**Comment by Celleb** [comment]
This is the difference.

Without source map support

Screenshot 2024-01-04 at 18 07 49

With source map support

Screenshot 2024-01-04 at 18 07 10

**Comment by p-mcgowan** [comment]
@Celleb yeah it doesn't have to do with webpack.

I use source map support regularly, but it's effectively a dev dependency - so anyone not using it now has another dep installed by default and gets nothing out of it.

it's trivial to add either manually through server.ts or even just modify your package json script to require it inline.

For these reasons, I think it's not super well-suited as a default for the base. 

This might be a great use case for [template extensions](https://acr-lfr.github.io/generate-it/#/_pages/features?id=overriding-template-code-with-code-from-another-source), which could probably use some love in the docs with usage examples. In this case, you can simply add in things like extra package scripts and dev deps quite easily, while keeping the base template as light as possible.

**Comment by Celleb** [comment]
@p-mcgowan you've to agree that it doesn't make sense to develop without source map support. Development is about your source files and not really your build. Therefore, I still think this should be part of the template. Most frameworks offer this as part of the base. You can look at nestjs for example. We can go on about personal opinions but practice from other libraries and frameworks shows this should be part of base. I also believe it is more than just for dev. Source maps are quite handy for your logs in production. They're quite resourceful for remote loggers like sentry or new relic or bugsnag.

**Comment by j-d-carmichael** [comment]
> > I'm not sure we need this in the default server stack as the stack is not using webpack.
> 
> I am not sure what webpack has to do with this. Maybe you can clarify.

As in i have only used source maps for webpack, typescript errors usually log the line correct with a few lines which does not need much to see where it came from.

**Comment by p-mcgowan** [comment]
@Celleb yes, I typically use source maps during development - I find them very useful and I almost exclusively use it during testing. That being said, I don't deploy them to prod, and I don't install source-map-support as a prod dep with a default require in the codebase. How I usually do it is install it as a dev dep, and modify a script (typically tests) to run `node -r source-map-support/register` so that it doesn't fail at runtime trying to require a dev dep. Our deployments are meant to be as slim as possible - meaning no unused node modules, and no source maps (which as you mentioned are not even created in tsconfig by default so this actually does nothing other than add an unused dep).

If you or your team are using source maps in prod, then that's an exception to the norm - as john said, it's usually quite clear from the error / function name where the exception is thrown, but worst case you can just look into dist as well. As you said, it could be helpful to get ts line numbers in logs and that's a great use-case but I don't see that as being the default.

This pr simply installs a dev dep (in my mind) as a prod dep, requires it inline, and it's completely unused without tsconfig source maps (which for the same reasons, should not be in prod).

This is not a good default, and as I mentioned in the previous comment, it's also easy to run `npm i source-map-support` and modify your start script to require the lib inline so that it doesn't need to be hardcoded into the server.ts file. I think that's pretty reasonable since the alternative is making everyone who deploys js files install an unused dependency.

Additionally, as I mentioned before, if you and your team do in fact deploy source maps to prod, then using template extensions to add this behaviour (including the updated tsconfig) would be the best bet here. They are designed specifically to be used for cases like this that either have downsides as a default, or for custom functionality that your team prefers to use.

I hope that makes sense - as mentioned, I find source map support incredibly useful during development as you do, it's just a question of it being sensible as a default for everyone.

**Comment by j-d-carmichael** [comment]
@Celleb i've started using this in some services on prod. not really noticed any impact on performance.. 

however I would create a separate repo and using the injection pattern to modify if i were you.

You can see an example in this repo:
https://github.com/acr-lfr/gen-it-ts-server-inject-rmq/blob/main/.nodegenrc

This will give you the function you need without extending this tpl.

But, I will close this PR now :)

**Comment by Celleb** [comment]
@j-d-carmichael how has experience been so far with source maps in production?

**Pull request closed without merging**
